import type { MetricLineage } from "@mini-terminal/shared";

type LineageDef = Omit<MetricLineage, "sampleNormalizedRows" | "sampleRawLogs">;

export const LINEAGE: Record<string, LineageDef> = {
  daily_fee_estimate: {
    metricName: "Daily Fee Estimate",
    description:
      "Estimated fees generated by swaps each day, calculated using a token0-denominated simplification. For each swap, the absolute value of amount0 is converted to token units and multiplied by the pool fee tier (0.05%). This is a transparent demo approximation — production systems would account for token direction and price.",
    formula: "daily_fee_estimate = SUM(ABS(amount0) / 10^decimals × fee_tier) grouped by day",
    sourceEvents: ["Swap"],
    sourceRawFiles: ["data/raw/logs.swap.json"],
    sourceIntermediateFiles: ["data/intermediate/swaps.parquet"],
  },
  daily_net_liquidity: {
    metricName: "Daily Net Liquidity Change (USD)",
    description:
      "USD-equivalent net capital flow from LPs. WETH price is derived from the pool's own swap data as a volume-weighted average: SUM(|USDC volume|) / SUM(|WETH volume|). Net WETH is converted at that price and added to net USDC. This avoids an external oracle dependency while giving a single, intuitive dollar figure.",
    formula: "net_usd = net_usdc + (net_weth × weth_price_usdc), where weth_price_usdc = SUM(|amount1|/10^6) / SUM(|amount0|/10^18) from swaps, grouped by day",
    sourceEvents: ["Swap", "Mint", "Burn"],
    sourceRawFiles: ["data/raw/logs.swap.json", "data/raw/logs.mint.json", "data/raw/logs.burn.json"],
    sourceIntermediateFiles: ["data/intermediate/swaps.parquet", "data/intermediate/mints.parquet", "data/intermediate/burns.parquet"],
  },
  daily_active_wallets: {
    metricName: "Daily Active Wallets by Role",
    description:
      "Unique wallets interacting with the pool each day, classified by role. Swappers appear in Swap events (sender or recipient). Liquidity providers appear in Mint or Burn events (owner). Wallets in both categories on the same day are classified as 'both'.",
    formula:
      "Classify each wallet per day as swapper (Swap sender/recipient), LP (Mint/Burn owner), or both. Count distinct wallets per role.",
    sourceEvents: ["Swap", "Mint", "Burn"],
    sourceRawFiles: ["data/raw/logs.swap.json", "data/raw/logs.mint.json", "data/raw/logs.burn.json"],
    sourceIntermediateFiles: [
      "data/intermediate/swaps.parquet",
      "data/intermediate/mints.parquet",
      "data/intermediate/burns.parquet",
    ],
  },
  daily_swap_count: {
    metricName: "Daily Swap Count",
    description: "Number of decoded Swap events per day.",
    formula: "daily_swap_count = COUNT(swaps) grouped by day",
    sourceEvents: ["Swap"],
    sourceRawFiles: ["data/raw/logs.swap.json"],
    sourceIntermediateFiles: ["data/intermediate/swaps.parquet"],
  },
  daily_volume_proxy: {
    metricName: "Daily Volume Proxy",
    description:
      "A proxy for daily swap volume using the absolute token0 amount. This is not perfect economic volume — it is a transparent, consistent proxy suitable for a demo. In production, you would apply price feeds and account for both token directions.",
    formula: "daily_volume_proxy = SUM(ABS(amount0) / 10^decimals) grouped by day",
    sourceEvents: ["Swap"],
    sourceRawFiles: ["data/raw/logs.swap.json"],
    sourceIntermediateFiles: ["data/intermediate/swaps.parquet"],
  },
  top_wallets: {
    metricName: "Top Interacting Wallets",
    description:
      "Wallets ranked by total interaction count across Swap, Mint, and Burn events. Each wallet is classified as swapper, liquidity_provider, or both based on which event types they appear in.",
    formula: "Count swap/mint/burn interactions per wallet, classify role, order by total_interactions DESC",
    sourceEvents: ["Swap", "Mint", "Burn"],
    sourceRawFiles: ["data/raw/logs.swap.json", "data/raw/logs.mint.json", "data/raw/logs.burn.json"],
    sourceIntermediateFiles: [
      "data/intermediate/swaps.parquet",
      "data/intermediate/mints.parquet",
      "data/intermediate/burns.parquet",
    ],
  },
};
